view:
  site:
    needLoginArticleReadCount: 30 # 需要登录才能阅读的文章阅读次数
    zsxqArticleReadCount: 20 # 知识星球用户才能阅读的文章阅读次数统计间隔，单位：分钟
    websiteName: 天澜社区
    websiteLogoUrl: https://paicoding.com/img/icon.png
    websiteFaviconIconUrl: https://paicoding.com/img/icon.png
    zsxqUrl: https://paicoding.com/article/detail/314
    zsxqPosterUrl: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/javabetter.jpg
    contactMeTitle: 联系我 - 青也前端
    contactMeWxQrCode: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png
    contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 打造人人可用的技术社区
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: http://127.0.0.1:${server.port}
    welcomeInfo: 欢迎来到天澜社区，戳<a href="/article/detail/15">天澜社区全方位视角解读</a>了解我们
    oss: